### PR TITLE
"fix" tab detection

### LINKED ISSUE #3: Broken on newer Atom versions
Loading a grammar seems to reset the `TextEditor`s indentation settings. We could kinda hack around that by changing [this](https://github.com/JunoLab/atom-indent-detective/blob/3e6479194b4aa1cb8aae4ac27caaac3b87023780/lib/indent-detective.coffee#L8) to `setTimeout (=> @get()), 500`, but a) is super hacky and b) doesn't work for deserialized editors when Atom starts up. I then tried adding another listener for `ed.observeGrammar` and call `@run()` from there, but that *also* doesn't seem to work properly.

Any other ideas, @MikeInnes?

### PR DESCRIPTION
**Pull request by pfitzseb**
fixes #3.
Yes, I do feel sufficiently bad about doing things this way, but other more subtle attempts of fixing this didn't work for deseiralized editors at all.

### CODE REVIEW

**Comment by pfitzseb** [comment]
@MikeInnes This should be good to merge I think. With this issue fixed we can then include indent-detective in Juno and never again have to argue about https://github.com/JuliaEditorSupport/atom-language-julia/pull/95. :)

**Comment by MikeInnes** [comment]
I'm worried about memory leaks, but we can perhaps use a weak set for that?

**Comment by pfitzseb** [comment]
Alright, I think everything should be cleaned up properly now :)

**Comment by MikeInnes** [comment]
Great, although I was also thinking about what happens if you just open and close a lot of editors within one session. Seems closed editors will stick around in that set forever.

**Comment by pfitzseb** [comment]
[No.](https://github.com/JunoLab/atom-indent-detective/pull/4/files#diff-01d6268128d8353e0dfd178edb83d448R15)

**Comment by MikeInnes** [comment]
Ah I see, good stuff.

**Pull request merged**
